### ISSUE TITLE
When sensors are close to each other, as in a ring, clearance of one sensor can clean obstacles on others

### ISSUE THREAD

**Issue by corot** [DLu/navigation_layers#22]
I noticed that this happen because we update a rectangular region containing the sensor's origin and left and right sides of sonar cone. So the corners near the origin easily overlap with the area covered by neighbor sensors in a ring. If a neighbor is sensing an obstacle near the origin, and our sensor is clearing a big area, the close obstacle can be removed. This gets solved updating only the mentioned  triangle.

I did a simple implementation of this change...  If you think it makes sense, I'll clean and make a PR

**Comment by DLu** [comment]
Can you give me a quick diagram first? I'm not quite sure what's happening.

**Comment by corot** [comment]
Let me try... I have faked the code to set the whole area affected by a single sonar as a lethal obstacle, just to see clearly its shape. With current code, one single sensor looks like [this](https://www.dropbox.com/s/uarov3f880z2yet/now.png?dl=0) (Hope you use dropbox... tell me if not!)
So you can see that, if clearing, this squared area can clean obstacles detected by the neighboring sonar (that are disabled for clarity).
With my proposed modification, the area modified by a single sonar only invades the neighboring's one if the detection cones overlaps: [capture](https://www.dropbox.com/s/3yk2t2v7h8c15ts/modif.png?dl=0), so sensors don't affect each other with current fov (pi/10)

**Comment by DLu** [comment]
The layer updates the values according to a probability model. 
https://github.com/DLu/navigation_layers/blob/hydro/range_sensor_layer/src/range_sensor_layer.cpp#L325
This includes the entire box, which may not be optimal, but shouldn't lead to inappropriately clearing out other close-by sensors.

**Comment by corot** [comment]
True, but when clear_on_max_range is on, the whole rectangular area is cleaned, affecting neighbors. Is easy to replicate with the dynamic reconfigure: just choose two close sensors, one detecting a near obstacle, one free up to his max range, and enable/disable the clear_on_max_range checkbox: you should see how the "free" sensor clears it's neighbor area when clear_on_max_range is on (and normally not if off... or at least is much more difficult to replicate)

**Comment by DLu** [comment]
Ok, I see the problem now. It goes back to b702525a6d1a18199c44c6ced375d6342aa83a16 and the fact that the max reading behavior doesn't use the sensor model and instead just uses 0. 

@MattDerry - In your use case, did it make sense to clear out the ENTIRE rectangle?

**Comment by MattDerry** [comment]
My use case didn't really have a problem with this because our sensor density was so sparse that we never ran in to this case, we didn't actually have a need for the entire rectangle to be cleared out.  This was just an oversight caused by a desire for a simple fix, which means it was probably the incorrect way for me to do it.

**Comment by corot** [comment]
Interesting nobody else have the same problem... Well, I have the code ready for a PR, if you find it makes sense.

**Comment by DLu** [comment]
Pull request is welcome!

**Comment by nxdefiant** [comment]
Looks like I have the same problem but using only two sensors. Using the fork and setting inflate_cone=0 fixes the problem.

The problem is visualized on the following screenshot:
![screenshot_no_obstacle](https://user-images.githubusercontent.com/885742/30122236-1e887764-932e-11e7-86a8-2d8515fd10d5.png)
The range sensor clearly detects an obstacle, but nothing is in the costmap because it is cleared by the other range sensor with clear_on_max_reading=true.

Now the same scenario with inflate_cone=0.
![screenshot_obstacle_inflate_cone_zero](https://user-images.githubusercontent.com/885742/30122247-248233da-932e-11e7-8c8b-9cc8ea577734.png)

**Comment by corot** [comment]
mmm...  I was about to make a PR for this...  but it's there since May 2016! :astonished:
https://github.com/DLu/navigation_layers/pull/30
